from PyQt5 import QtCore, QtWidgets
from ui_styles import DARK_BTN, DIALOG_BG, LABEL_TITLE, LOG_BOX


class HelpDialog(QtWidgets.QDialog):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setWindowTitle("ModuTEC — Ayuda")
        self.setMinimumSize(560, 460)
        self.setStyleSheet(DIALOG_BG)
        
        self.setWindowFlags(
            self.windowFlags() & ~QtCore.Qt.WindowContextHelpButtonHint
        )

        lay = QtWidgets.QVBoxLayout(self)
        lay.setContentsMargins(16, 16, 16, 16)
        lay.setSpacing(10)

        title = QtWidgets.QLabel("User Guide — ModuTEC Monitor")
        title.setStyleSheet(LABEL_TITLE)
        title.setAlignment(QtCore.Qt.AlignCenter)
        lay.addWidget(title)

        text = QtWidgets.QTextEdit()
        text.setReadOnly(True)
        text.setStyleSheet(LOG_BOX)
        text.setHtml("""

    <style>
    body { color: #ecf0f1; font-family: Arial; }
    h1  { color: #3498db; }
    h2  { color: #5dade2; margin-top: 14px; }
    p   { margin: 4px 0 10px 0; }
    li  { margin: 3px 0; }
    b   { color: #76f507; }
    </style>

    <h1>Quick User Guide</h1>

    <p>
    The ModuTEC Monitor application allows real-time visualization and analysis
    of modulation and demodulation techniques executed on the embedded system.
    </p>

    <h2>1. Device Connection</h2>
    <ul>
    <li>Connect the Raspberry Pi Pico to the computer using USB.</li>
    <li>Select the correct COM port from the available list.</li>
    <li>Verify that the device is detected before starting transmission.</li>
    </ul>

    <h2>2. Starting the Monitor</h2>
    <ul>
    <li>Press the <b>Run</b> button to begin data acquisition.</li>
    <li>The monitor will start receiving signal blocks from the embedded system.</li>
    <li>Press <b>Stop</b> to end the execution safely.</li>
    </ul>

    <h2>3. Signal Visualization</h2>
    <ul>
    <li><b>Original Signal:</b> Input signal generated by the embedded system.</li>
    <li><b>Modulated Signal:</b> Signal after applying the modulation technique.</li>
    <li><b>Demodulated Signal:</b> Reconstructed signal obtained after demodulation.</li>
    </ul>

    <h2>4. Configuration System</h2>
    <ul>
    <li>The monitor supports external configuration files.</li>
    <li>Parameters such as sampling frequency, block size and modulation settings can be modified.</li>
    <li>Configurations can be loaded directly from the configuration menu.</li>
    </ul>

    <h2>5. Supported Techniques</h2>
    <ul>
    <li>AM (Amplitude Modulation)</li>
    <li>ASK/OOK (Amplitude Shift Keying / On-Off Keying)</li>
    </ul>

    <h2>6. Performance Recommendations</h2>
    <ul>
    <li>Use stable USB connections during execution.</li>
    <li>Avoid running multiple serial applications simultaneously.</li>
    <li>Use moderate sampling frequencies to maintain stable real-time visualization.</li>
    </ul>

    <h2>7. System Status and Logs</h2>
    <ul>
    <li>The log panel displays connection and execution events.</li>
    <li>Error messages related to communication or synchronization are also reported.</li>
    </ul>

    <p>
    ModuTEC was developed as an embedded signal processing platform for
    real-time experimentation and visualization of analog and digital
    modulation techniques.
    </p>
    """)
        lay.addWidget(text)

        close_btn = QtWidgets.QPushButton("Cerrar")
        close_btn.setStyleSheet(DARK_BTN)
        close_btn.clicked.connect(self.accept)
        lay.addWidget(close_btn, alignment=QtCore.Qt.AlignRight)